### ISSUE TITLE
Nie można odpalić transportu w tle.

### ISSUE THREAD

**Issue by mky** [Jajcus/jggtrans#28]
OS: FreeBSD 8.3
jggtrans: git (20130510)
Pakiety: gettext-0.18.1.1_1 libiconv-1.14_1 glib-2.34.3 pcre-8.32 pl-libgadu-1.11.2,1 libidn-1.26 expat-2.0.1_2 pkgconf-0.9.2_1

Po kompilacji najnowszego jggtrans wraz z pakietami wymienionymi wyżej, nie można uruchomić transportu w tle (wiesza się). Ubić można tylko przez 'kill -9', na 'kill -TERM' nie reaguje. Po odpaleniu na pierwszym planie (-f) pracuje poprawnie.

**Comment by Jajcus** [comment]
Od dawna unikam odpalania czegoś takiego „w tle” (bardzo kiepski sposób 
zarządzania procesami), ale powinno to działać. Podejrzewam, że jeśli
jest problem to związany z systemem (FreeBSD).

Jesteś w stanie wybadać na czym to się dokładnie wiesza? jakieś
strace/gdb/czy-co-tam-jest-we-freebest

**Comment by mky** [comment]
Po odpaleniu w tle, jggtrans uruchamia pierwszą sesję GG i dalej już wisi:

2013-05-10 17:44:21 handshake OK
2013-05-10 17:44:21 Creating session for 'xxx@xxxxxxxxxxxxxx/xxxx'
2013-05-10 17:44:21 Warning: Trying to log in on server 0

Więcej już nic nie loguje. Status procesu to 'piperd' czyli czeka na jakiś odczyt z pipe do którego chyba nie dochodzi (?)

Output truss-a dla tego procesu udostępniam tutaj:
http://pastebin.com/raw.php?i=R4iDnmKm

**Comment by Jajcus** [comment]
Fixed via c5986408beb25f6da9896ba23048afb457a3d33d and e75f2c3866b5c6825ef60ed4cfde8e02303d9c20
